#!/usr/bin/env sh
# Render runs this as the Static Site "Build Command": sh build.sh
# It stamps the deployed git commit + build time into js/buildinfo.js
# so the on-screen version badge always matches what's actually live.

SHA="${RENDER_GIT_COMMIT:-$(git rev-parse HEAD 2>/dev/null || echo unknown)}"
SHORT=$(printf "%s" "$SHA" | cut -c1-7)
DATE=$(date -u +"%Y-%m-%d %H:%MZ")

cat > js/buildinfo.js <<EOF
/* AUTO-GENERATED by build.sh at deploy time — do not edit */
window.JARS_COMMIT = "${SHORT}";
window.JARS_BUILT  = "${DATE}";
EOF

echo "buildinfo stamped: ${SHORT} @ ${DATE}"
